import { expect, test } from "bun:test"
import { renderToStaticMarkup } from "react-dom/server"
import type { Job } from "@/shared/job-types"
import { DatasheetReference } from "@/web/components/datasheet-reference"

const job: Job = {
  job_id: "job_1",
  file_name: "component.pdf",
  created_at: "2026-07-24T00:00:00.000Z",
  display_status: "complete",
  is_complete: true,
  has_errors: false,
  logs: [],
  evidence_available: true,
}

test("the datasheet reference renders as a non-interactive image", () => {
  const html = renderToStaticMarkup(
    <DatasheetReference
      job={job}
      artifact="component"
      component_view="footprint"
      on_component_view_change={() => {}}
    />,
  )

  expect(html).toContain('<img class="datasheet-reference-image"')
  expect(html).not.toContain("<a")
})

test("an AI-generated application identifies its origin instead of showing the reference figure", () => {
  const html = renderToStaticMarkup(
    <DatasheetReference
      job={{
        ...job,
        typical_applications: {
          default_application_id: "reference",
          applications: [
            {
              application_id: "reference",
              title: "Datasheet reference",
              origin: "datasheet_reference",
            },
            {
              application_id: "level-shifter",
              title: "Level shifter",
              origin: "ai_generated",
            },
          ],
        },
      }}
      artifact="typical_application"
      component_view="footprint"
      on_component_view_change={() => {}}
      application_id="level-shifter"
    />,
  )

  expect(html).toContain("Generated by AI")
  expect(html).toContain("grounded in extracted datasheet constraints")
  expect(html).not.toContain('<img class="datasheet-reference-image"')
})
